runtime: python311 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  APPENGINE_URL: https://slidigital.uc.r.appspot.com

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /mysite/randing/
  static_dir: /mysite/randing/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto